services:
  backend:
    container_name: backend
    image: shakthivelk24/virtualassisstant-backend:${IMAGE_TAG}

    ports:
      - "5000:5000"

    env_file:
      - ./server/.env

    restart: unless-stopped

    networks:
      - virtualassisstant-network

  frontend:
    container_name: frontend
    image: shakthivelk24/virtualassisstant-frontend:${IMAGE_TAG}

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - virtualassisstant-network

networks:
  virtualassisstant-network:
    driver: bridge